config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'recipe/index'
  get 'recipe/search', to:'recipe#search', as: 'recipe_search'
  get 'recipe/show/:id', to: 'recipe#show', as: 'recipe_show'
  get 'recipe/detail/:id', to: 'recipe#detail', as: 'recipe_detail'

  resources :ingredients
  root to: "welcome#index"

  #match 'same_directors/:id' => 'movies#same_directors', via: :all, :as => 'same_directors'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
    # validates_uniqueness_of :item
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  ## ------这个不要用！！！！------ ##
  # @@apiKey = "7f274a56343748968771ed0642f79c6c"
  ## ------下面的都可以用------ ##
  # @@apiKey = "2e644af47d964b57a970710eec23c5bb"
  # @@apiKey = "06c5643caf1b4d4fb78fa436b127b236"
  # @@apiKey = "2f0cb560447f48f6a6c3d12efee50385"
  # @@apiKey = "fa6f5860fc5c4706bac0c44362038232"
  # @@apiKey = "c2c323be3715495098a70f097b74144d"
  @@apiKey = "5b3ec929ab684d1cb2b060f5b7eb2245"
  #@@apiKey = "0578306e10a44e4bae97ee439fefc5ae"
  #@@apiKey = "23ad34506bd74105828e41a179fda832"


  def show
    id = params[:id] # retrieve movie ID from URI route
    @ingredient = Ingredient.find(id) # look up ingredient by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @ingredients = Ingredient.all
  end

  def create
    cparams = ingredient_params
    if cparams['item'].empty?
      flash[:notice] = "Error - please input a valid name"
      render :new
    elsif cparams['quantity'].to_i <=0
      flash[:notice] = "Error - please input a valid quantity"
      render :new
    else
      cparams['item'] = cparams['item'].titleize
      if !Ingredient.find_by_item(cparams['item']).nil?
        @ingredient = Ingredient.find_by_item(cparams['item'])
        begin 
          @ingredient.update_attributes!(cparams)
          flash[:notice] = "#{@ingredient.item} was successfully updated."
          redirect_to ingredients_path
        rescue
          flash[:notice] = "Error - please input a valid name and quantity"
          render :new
        end
      else
        @ingredient = Ingredient.new(cparams)
        begin 
          @ingredient.save
          flash[:notice] = "#{@ingredient.item} was successfully created."
          redirect_to ingredients_path
        rescue
          flash[:notice] = "Error - please input a valid name and quantity"
          render :new
        end
      end
    end
  end


  def edit
    @ingredient = Ingredient.find params[:id]
    api_info = HTTParty.get("https://api.spoonacular.com/food/ingredients/search?query="+@ingredient.item.downcase, {query: {apiKey: @@apiKey}}).parsed_response
    if !api_info["results"].nil? && !api_info["results"].empty?
      api_id = api_info["results"][0]["id"] 
      nutrient_info = HTTParty.get("https://api.spoonacular.com/food/ingredients/"+api_id.to_s+"/information?amount="+@ingredient.quantity.to_s, {query: {apiKey: @@apiKey}}).parsed_response
      @nutrients = nutrient_info["nutrition"]["nutrients"]
    else
      @nutrients = ""
    end   
  end

  def update
    @ingredient = Ingredient.find params[:id]
    @ingredient.update_attributes!(ingredient_params)
    flash[:notice] = "#{@ingredient.item} was successfully updated."
    redirect_to ingredient_path(@ingredient)
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    item = @ingredient.item
    @ingredient.destroy
    flash[:notice] = "Ingredient '#{item}' deleted."
    redirect_to ingredients_path
  end

  # private
  # # Making "internal" methods private is not required, but is a common practice.
  # # This helps make clear which methods respond to requests, and which ones do not.
  def ingredient_params
      params.require(:ingredient).permit(:item, :quantity, :quantity_date)
      # params.require(:ingredient).permit(:item, :quantity, :quantity_date)
  end
end

app/views/ingredients/edit.html.erb
<div class="hero_image" class="d-flex align-items-center " style="height:800px; width: 100%;border:1px solid black; background-image: url(<%= 'https://source.unsplash.com/4y3Dqy2tTM4' %>);background-size: cover;background-position: center;background-attachment:fixed;
    overflow:scroll;">
  <div class="d-flex p-2 bd-highlight">
    <div class="d-flex justify-content-around" style="width:380px;height:380px;border-style: none;background-color: transparent;">
    </div>

    <div class="card d-flex justify-content-center" style="width: 300px;height:600px;border-style: none;background-color: transparent;">
      <%= form_tag ingredient_path(@ingredient), :method => :put do %>
        <%= label :ingredient, :quantity, 'Quantity', :class => 'col-form-label'  %>
        <%= text_field :ingredient, :quantity, class: 'form-control' %>
        <!--   <%= label :ingredient, :expiration_date, 'Expiration Date', :class => 'col-form-label'  %>
        <%= date_select :ingredient, :expiration_date, {}, :class => 'form-control col-2 d-inline' %>-->
        <br/>
        <%= submit_tag 'Update Ingredient Info', :class => 'btn btn-secondary' %>
        <%= link_to 'Cancel', ingredients_path, :class => 'btn btn-secondary' %>
      <% end %>
    </div> 
  </div>


  <br/>
  <% if @nutrients.length == 0 %>
  <h3>Nutrition Information Not Available! </h3>
  <% else %>
  <h3>Nutrition Information</h3>
  <div>
  <table class="table table-striped col-md-12" id="used">
    <tbody>
      <tr>
      <td>
          Name
      </td>
      <td>
          Amount
      </td>
      <td>
          Unit
      </td>
      <td>
          % of Daily Needs
      </td>
      </tr>
      <% @nutrients.each do |item| %>
        <tr>
          <td>
            <%= item['name'] %>
          </td>
          <td>
            <%= item['amount'] %>
          </td>
          <td>
            <%= item['unit'] %>
          </td>
          <td>
            <%= item['percentOfDailyNeeds'] %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <% end %>

</div>

app/views/ingredients/index.html.erb
<%#  Part 2: Start here... %>
<div class="hero_image" class="d-flex align-items-center " style="height:800px; width: 100%;border:1px solid black; background-image: url(<%= 'https://source.unsplash.com/4y3Dqy2tTM4' %>);background-size: cover;background-position: center;background-attachment:fixed;
    overflow:scroll;">
<table class="table table-striped col-md-12 align-self-center ml-4 mt-3" id="ingredients" style="width: 630px;">
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
<!--       <th>Expiration Date</th> -->
      <th>Make Changes</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td>
          <%= ingredient.item %>
        </td>
        <td>
          <%= ingredient.quantity %>
        </td>
<!--         <td>
          <%= date_select :ingredient, ingredient.expiration_date %>
        </td> -->
        <td>
          <%= link_to "More about #{ingredient.item}", edit_ingredient_path(ingredient) %>
        </td>
        <td>
          <%= button_to "Delete", ingredient_path(ingredient), :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/ingredients/new.html.erb
<div class="hero_image" class="d-flex align-items-center " style="height:600px; width: 100%;border:1px solid black; background-image: url(<%= 'https://source.unsplash.com/_XdU9Q5iFRE' %>);background-size: cover;background-position: center">
  <div class="d-flex justify-content-center h-100">

    <div class="card d-flex align-items-center align-self-center" style="width: 600px;height:400px;border-style: none;background-color: transparent;">
      <div class="card-body">
        <h2>Add new ingredients</h2>

        <%= form_tag ingredients_path, class: 'form' do %>
          <%= label :ingredient, :item, 'Item', :class => 'col-form-label'  %>
          <%= text_field :ingredient, :item, class: 'form-control' %>

          <%= label :ingredient, :quantity, 'Quantity', :class => 'col-form-label'  %>
          <%= text_field :ingredient, :quantity, class: 'form-control' %>

          <br/>
          <div style="text-align:center">  
            <%= submit_tag 'Confirm', :class => 'btn btn-secondary' %>
          </div> 
        <% end %>

        <br/><br/>
        <div style="text-align:center">    
          <a href="/ingredients" class="card-link btn btn-secondary">Back to List</a>
          <a href="/recipe/index" class="card-link btn btn-secondary">Create Recipe</a>
        </div> 
      </div>
    </div>

  </div>
</div>

app/views/ingredients/show.html.erb
<!--     <div class="container">
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg bg-primary text-white mb-3 pink-300" >
      <h1 class="title"><%= @ingredient.item %></h1>
    </nav>
    <div class="container">
 -->
 <div class="hero_image" class="d-flex align-items-center " style="height:600px; width: 100%;border:1px solid black; background-image: url(<%= 'https://source.unsplash.com/_XdU9Q5iFRE' %>);background-size: cover;background-position: center">

<div class="d-flex justify-content-center h-100">
  
<div class="card d-flex align-items-center align-self-center" style="width: 600px;height:400px;border-style: none;background-color: transparent;">
  <div class="card-body">
    <h5 class="card-title"><%= @ingredient.item %></h5>
    <p class="card-text">Quantity: <%= @ingredient.quantity %></p>
    <a href="/ingredients" class="card-link btn btn-secondary">Back to List</a>
    <a href="/ingredients/<%= @ingredient.id %>/edit" class="card-link btn btn-secondary">Show Nutrition Info</a>
  </div>
</div>
</div>
</div>

<!-- <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @ingredient.item %></h5>
    <p class="card-text">Quantity:<%= @ingredient.quantity %></p>
    <a href="/ingredients" class="card-link">Back to List</a>
    <a href="/ingredients/<%= @ingredient.id %>/edit" class="card-link">Show Nutrition Info</a>
  </div>
</div> -->

<!--  This file is app/views/movies/index.html.erb -->