config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'recipe/index'
  get 'recipe/search', to:'recipe#search', as: 'recipe_search'
  get 'recipe/show/:id', to: 'recipe#show', as: 'recipe_show'
  get 'recipe/detail/:id', to: 'recipe#detail', as: 'recipe_detail'

  resources :ingredients
  root to: "welcome#index"

  #match 'same_directors/:id' => 'movies#same_directors', via: :all, :as => 'same_directors'
end

app/controllers/recipe_controller.rb
require "json"
require "base64"

class RecipeController < ApplicationController
  ## ------这个不要用！！！！------ ##
  # @@apiKey = "7f274a56343748968771ed0642f79c6c"
  ## ------下面的都可以用------ ##
  # @@apiKey = "2e644af47d964b57a970710eec23c5bb"
  # @@apiKey = "06c5643caf1b4d4fb78fa436b127b236"
  # @@apiKey = "2f0cb560447f48f6a6c3d12efee50385"
  # @@apiKey = "fa6f5860fc5c4706bac0c44362038232"
  # @@apiKey = "c2c323be3715495098a70f097b74144d"
  # @@apiKey = "5b3ec929ab684d1cb2b060f5b7eb2245"
  # @@apiKey = "0578306e10a44e4bae97ee439fefc5ae"

  @@apiKey = "23ad34506bd74105828e41a179fda832"

  @@tags = [:cuisine, :intolerances, :diet, :type]
  @@ss = []
  @@api_list = []
  def get_steps_info(id)
    info = HTTParty.get("https://api.spoonacular.com/recipes/"+id.to_s+"/analyzedInstructions", {query: {apiKey: @@apiKey}}).parsed_response
    return info
  end

  def get_recipe_info(id, includeNutrition)
    info = HTTParty.get("https://api.spoonacular.com/recipes/"+id.to_s+"/information", {query: {includeNutrition: includeNutrition, apiKey: @@apiKey}}).parsed_response
    return info
  end

  def get_similar_recipes(id)
    info = HTTParty.get("https://api.spoonacular.com/recipes/"+id.to_s+"/similar", {query: {apiKey: @@apiKey}}).parsed_response
    return info
  end

  def detail_impl(params)
    obj = get_recipe_info(params['id'], true)
    #puts "--------------------------"
    #puts @obj
    return obj
  end


  def detail
    @obj = detail_impl(params)
    #puts "--------------------------"
    #puts @obj
  end

  def show
    ret = show_impl(params)
    @obj = ret[0]
    @step = ret[1]
    @similars = ret[2]
  end

  def show_impl(params)
    obj = get_recipe_info(params['id'], false)
    step = get_steps_info(params['id'])
    similars = get_similar_recipes(params['id'])
    return obj, step, similars
  end


  def index
    #get_recipes[1]
    @recipes = get_recipes[1].sort_by { |el| -el[5] }
    return @receipes
  end

  def search
    # site = "https://api.spoonacular.com/recipes/queries/analyze"
    # query_param = {q: params['search'], apiKey: @@apiKey}
    site = "https://api.spoonacular.com/recipes/complexSearch"
    query_param = {query: params['search'], apiKey: @@apiKey}

    # puts query_param
    @recipes = []
    objs= HTTParty.get(site, {query: query_param, header: {'Content-Type' => 'application/json'}}).parsed_response
    objs['results'].each do |obj|
      @recipes.push([obj['title'],obj['id']])
    end
  end
  # def recipe_params
  #   params.require(:recipe)
  # end

  #def load_recipe(title) 
  #  obj = nil
  #  File.open(title, 'r') do | f |
  #    content = f.read
  #    obj = JSON.parse(content)
  #  end

  #  return obj
  #end

  #def save_recipes(objs)
  #  objs.each do | obj |
  #    save_recipe(obj)
  #  end
  #end

  #def save_recipe(obj) 
  #  title = obj['title']
  #  #title = Base64.encode64(title)
  #  content = obj.to_json
  #  File.open(title, 'w') do | f |
  #    f.write(content)
  #  end
  #end

  def max_count(conds)
    count = 0
    conds.each do |k, v| 
      if v != 'Any' and v != 'None'
        count = count + 1
      end
    end
    count
  end



  def score(recipe, params)
    final_score = 0
    count = 0
  
    final_score += (@@ss & @@api_list).size * 0.2

    if not params["recipe"]["cuisine"] == "Any" and not recipe["cuisines"]==nil
      if recipe["cuisines"].include?(params["recipe"]["cuisine"])
        final_score += 1
        count += 1
      else
        final_score -= 1
      end
    end

    if not params["recipe"]["diet"] == "Any" and not recipe["diets"]==nil
      if recipe["diets"].include?(params["recipe"]["diet"])
        final_score += 1
        count += 1
      else
        final_score -= 1
      end
    end
      
    if not params["recipe"]["occasion"] == "Any" and not recipe["occasions"]==nil
      if recipe["occasions"].include?(params["recipe"]["occasion"])
        final_score += 1
        count += 1
      else
        final_score -= 1
      end
    end

    return final_score, count

  end


  def get_recipes
    items = get_ingredients

    @@ss = items.map do |item|
      item.item.downcase
    end
    
    if not params.keys().include?("recipe")
      params["recipe"]={"cuisine"=>"Any", "diet"=>"Any", "occasion"=>"Any"}
    end

    key = @@ss.join(',')
    num = 5
    site = "https://api.spoonacular.com/recipes/findByIngredients"
    query_param = {ingredients: key, number: num, apiKey: @@apiKey, ignorePantry: true}

    # puts query_param
    objs = HTTParty.get(site, {query: query_param, header: {'Content-Type' => 'application/json'}}).parsed_response

    @@api_list = []
    recipe_list = []
    obj_target_count = max_count(params['recipe'])

    objs.each do |obj|
      info = get_recipe_info(obj['id'], false)
      exts = info["extendedIngredients"]
      obj_score, obj_count = score(info, params)

      exts.each do |ext|
        @@api_list.append(ext["name"])
      end

      recipe_list.append([info["title"], info["cuisines"], info["diets"], info["occasions"], info["readyInMinutes"], obj_score, info['id']])

    end

    return @@api_list, recipe_list
  end

  def get_ingredients
    return Ingredient.where("quantity > 0")
  end

end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/recipe/detail.html.erb
<%= link_to "Back", :back, :class => 'btn btn-outline-secondary my-2 my-sm-0' %>
<h2>
    <%= @obj['title'] %>
<h2>

<div>
    <%= image_tag(@obj['image']) %>
</div>

<h3>Nutrition List</h3>
<div>
<table class="table table-striped col-md-12" id="used">
  <tbody>
    <tr>
    <td>
        Name
    </td>
    <td>
        Amount
    </td>
    <td>
        unit
    </td>
    </tr>
    <% @obj['nutrition']['nutrients'].each do |item| %>
      <tr>
        <td>
          <%= item['name'] %>
        </td>
        <td>
          <%= item['amount'] %>
        </td>
        <td>
          <%= item['unit'] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/recipe/index.html.erb
<div>
<%= form_tag recipe_index_path(), :method => :get, id: 'p' do %>
  <%= label :recipe, :cuisine, 'Cuisine', :class => 'col-form-label'  %>
  <%= select :recipe, :cuisine,options_for_select(['Any', 'American', 'Asian','British', 'Chinese', 'French', 'German', 'Greek', 'Italian', 'Japanese', 'Jewish', 'Korean', 'Mediterranean', 'Mexican', 'Spanish', 'Thai', 'Vietnamese']), :class => 'form-control' %>

  <%= label :recipe, :diet, 'Diet', :class => 'col-form-label'  %>
  <%= select :recipe, :diet,options_for_select(['Any', 'gluten free', 'dairy free', 'ovo vegetarian', 'lacto ovo vegetarian', 'paleo', 'pescetarian', 'primal', 'vegan', 'vegetarian', 'ketogenic', 'whole 30']), :class => 'form-control' %>

  <%= label :recipe, :occasion, 'Occasion', :class => 'col-form-label'  %>
  <%= select :recipe, :occasion, options_for_select(['Any', 'spring', 'summer', 'fall', 'winter', 'Birthday', 'Christmas', 'Halloween', "New Year's Eve", 'Thanksgiving', "Valentine's Day"]), :class => 'form-control' %>


  <%= submit_tag 'Update User Preference', :class => 'btn btn-outline-secondary my-2 my-sm-0' %>
<% end %>
</div>

<%#  Part 2: Start here... %>
<div class="hero_image" class="d-flex align-items-center " style="height:700px; width: 100%;border:1px solid black; background-image: url(<%= 'https://source.unsplash.com/Q7PclNhVRI0' %>);background-size: cover;background-position: center;background-attachment:fixed;
    overflow:scroll;">
<table class="table table-striped col-md-12 align-self-center ml-4 mt-3" id="ingredients" style="width: 100%;">
  <thead>
    <tr>
      <th>Item</th>
      <th>Details</th>
      <th>Steps</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each_with_index do |recipe, idx| %>
      <tr>
        <td>
          <%= recipe[0]%>
          <% if !recipe[1].empty?%>
          <% recipe[1].each do |type| %>
            <button class="btn btn-secondary"><%= type%></button>
            <%end%>
          <% end %>
          <% if !recipe[2].empty?%>
          <% recipe[2].each do |type| %>
            <button class="btn btn-secondary"><%= type%></button>
            <%end%>
          <% end %>
          <% if !recipe[3].empty?%>
          <% recipe[3].each do |type| %>
            <button class="btn btn-secondary"><%= type%></button>
            <%end%>
          <% end %>

          <% if !recipe[4].nil?%>
            <button class="btn btn-secondary"><%= recipe[4]%></button>
          <% end %>
        </td>
        <td>
          <%= link_to "details", recipe_detail_path(recipe[6]), :class => 'btn btn-secondary' %>
        </td>
        <td>
          <%= link_to "steps", recipe_show_path(recipe[6]), :class => 'btn btn-secondary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>







<!-- <%= link_to "Ingredient", ingredients_path, :class => 'btn btn-primary' %>
<%= link_to "Main Page", '/', :class => 'btn btn-primary' %> -->

app/views/recipe/search.html.erb
<div class="hero_image" class="d-flex align-items-center " style="height:700px; width: 100%;border:1px solid black; background-image: url(<%= 'https://source.unsplash.com/Q7PclNhVRI0' %>);background-size: cover;background-position: center;background-attachment:fixed;
    overflow:scroll;">
<% if @recipes.empty? %>
<div class="d-flex align-items-center">
<h2>Sorry, we could not find the recipe you want :(</h2>
</div>
<% else %>
<table class="table table-striped col-md-12 align-self-center ml-4 mt-3" id="ingredients" style="width: 100%;">
  <thead>
    <tr>
      <th>Available Recipe</th>
      <th>Details</th>
      <th>Steps</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each_with_index do |recipe, idx| %>
      <tr>
        <td>
          <%= recipe[0]%>
        </td>
        <td>
          <%= link_to "details", recipe_detail_path(recipe[1]), :class => 'btn btn-secondary' %>
        </td>
        <td>
          <%= link_to "steps", recipe_show_path(recipe[1]), :class => 'btn btn-secondary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/recipe/show.html.erb
<%= link_to "Back", :back, :class => 'btn btn-outline-secondary my-2 my-sm-0' %>
<h2>
    <%= @obj['title'] %>
<h2>

<div>
    <%= image_tag(@obj['image']) %>
</div>

<h3>Step List</h3>
<% if @step[0] == nil ||  @step[0]['steps'].length == 0 %>

<%= link_to "Info on external website", @obj['sourceUrl'] %>

<% else %>
<div>
<table class="table table-striped col-md-12" id="used">
  <tbody>
    <% @step[0]['steps'].each do |item| %>
      <tr>
        <td>
          <%= item['step'] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<% end %>

<h3>Similar recipes</h3>
<div>
<table class="table table-striped col-md-12" id="used">
  <tbody>
    <% @similars.each do |item| %>
      <tr>
        <td>
          <%= link_to item['title'], recipe_show_path(item['id'])  %>
        </td>
        <td>
          <%= link_to "details", recipe_detail_path(item['id']), :class => 'btn btn-secondary' %>
        </td>
        <td>
          <%= link_to "steps", recipe_show_path(item['id']), :class => 'btn btn-secondary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<h3>Wine pairing recommendations</h3>
<div>
<table class="table table-striped col-md-12" id="used">
  <tbody>
    <%if @obj['winePairing']['productMatches'] %>
    <% @obj['winePairing']['productMatches'].each do |item| %>
      <tr>
        <td>
          <%= item['title'] %>
        </td>
        <td>
          <%= item['price'] %>
        </td>
        <td>
          <%= link_to 'link', item['link'] %>
        </td>
      </tr>
    <% end %>
    <% else %>
      <tr>
        <td>
          no product match
        </td>
      </tr>

    <% end %>
  </tbody>
</table>
</div>