config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'recipe/index'
  get 'recipe/search', to:'recipe#search', as: 'recipe_search'
  get 'recipe/show/:id', to: 'recipe#show', as: 'recipe_show'
  get 'recipe/detail/:id', to: 'recipe#detail', as: 'recipe_detail'

  resources :ingredients
  root to: "welcome#index"

  #match 'same_directors/:id' => 'movies#same_directors', via: :all, :as => 'same_directors'
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Chef Effortless</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,500;1,200&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
      <a class="navbar-brand" href="/">Chef Effortless</a>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Ingredient", ingredients_path, :class => 'btn' %>
          </li>
          <li>
            <%= link_to "Add Ingredient", new_ingredient_path, :class => 'btn' %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Recipe",recipe_index_path, :class => 'btn' %>
          </li>
        </ul>
        <%= form_tag recipe_search_path(), :method => :get,:class => 'form-inline my-2 my-lg-0', id: 'Search' do %>
        <%= text_field_tag(:search, params[:search],:class => 'form-control mr-sm-2') %>
        <%= submit_tag 'Search Recipe in Mind', :class => 'btn btn-outline-secondary my-2 my-sm-0' %>
        <% end %>
        
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn' %>
      </div>
      <% end %>
    </nav>
  </div>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
    </div>
  </body>
</html>